config/routes.rb
Payetapinte::Application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  resources :bars do
    resources :comments
  end

  resources :preview

  resources :page

  root :to => "welcome#index"

end

app/models/bar.rb
class Bar < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude, :location, :name, :price, :start_happy, :end_happy, :price_happy

  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :price, presence: true,
            numericality: { only_float: true }
  validates :address, presence: true,
            length: { minimum: 10 }

  validates_uniqueness_of :address

  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude, :address => :address
  after_validation :geocode, :reverse_geocode

end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  layout "admin"
  http_basic_authenticate_with :name => ENV["ADMIN_AUTH"], :password => ENV["ADMIN_PASSWORD"], :except => [:index]
  helper_method :sort_column, :sort_direction

  # GET /bars
  # GET /bars.json
  def index
    @bars = Bar.order(sort_column+" "+sort_direction)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bars }
    end
  end

  # GET /bars/1
  # GET /bars/1.json
  def show
    @bar = Bar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bar }
    end
  end

  # GET /bars/new
  # GET /bars/new.json
  def new
    @bar = Bar.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bar }
    end
  end

  # GET /bars/1/edit
  def edit
    @bar = Bar.find(params[:id])
  end

  # POST /bars
  # POST /bars.json
  def create
    @bar = Bar.new(params[:bar])


    respond_to do |format|
      if @bar.save
        format.html { redirect_to root_url, notice: 'Bar was successfully created.' }
        format.json { render json: @bar, status: :created, location: @bar }
      else
        format.html { render action: "new" }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bars/1
  # PUT /bars/1.json
  def update
    @bar = Bar.find(params[:id])

    respond_to do |format|
      if @bar.update_attributes(params[:bar])
        format.html { redirect_to @bar, notice: 'Bar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bars/1
  # DELETE /bars/1.json
  def destroy
    @bar = Bar.find(params[:id])
    @bar.destroy

    respond_to do |format|
      format.html { redirect_to bars_url }
      format.json { head :no_content }
    end
  end

  private

  def sort_column
    Bar.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/bars_helper.rb
module BarsHelper
end

app/views/bars/_form.html.erb
<div class="bar-form" onload="initialize()">
    <%= form_for(@bar) do |f| %>
      <% if @bar.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@bar.errors.count, "error") %> prohibited this bar from being saved:</h2>

          <ul>
          <% @bar.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="basic">
        <h3>Nom du bar :</h3>
        <%= f.text_field :name%>
        <h3>Prix de la Pinte : </h3>
        <%= f.text_field :price %>
        <h3>Emplacement du bar :</h3>
        <div class="field" id="locationField">
          <%= f.text_field :address, autocomplete: 'off' %>
        </div>
      </div>


      <div class="happy">
        <hr>
        <h3>Happy Hours ! </h3>
        <small>Si il n'y a pas d'happy hour, ou qu'elles n'ont pas été renseignées, laissez les valeurs "début" et "fin" égales. </small>
        <h4>Début happy :</h4>
        <%= f.time_select :start_happy  %>
        <h4>Fin happy :</h4>
        <%= f.time_select :end_happy  %>
        <h4>Prix pendant l'happy hour :</h4>
        <%= f.text_field :price_happy, placeholder: 'Prix en Happy Hours...' %>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
</div>

app/views/bars/edit.html.erb
<h1>Editer un Bar : </h1>

<%= render 'form' %>
<%= javascript_tag "autocompleteNew()" %>


<%= link_to 'Show', @bar %> |
<%= link_to 'Back', bars_path %>

app/views/bars/index.html.erb
<h1>Listing des <%= @bars.length%> bars !</h1>
<h2><%= link_to 'New Bar', new_bar_path %></h2>
<div class="info">

</div>

<table class="table table-striped datatable-searchable">
  <tr class="top-table">
    <th>N°</th>
    <th><%= sortable "name", "Nom" %></th>
    <th><%= sortable "price", "Prix" %></th>
    <th>Adresse</th>
    <th>HappyHours</th>
    <th><%= sortable "price_happy", "Happy Prix !" %></th>
    <th><%= sortable "created_at", "Création" %></th>
    <th>Show</th>
    <th>Edit</th>
    <th>Destroy</th>
  </tr>

<% @bars.each_with_index do |bar, index| %>
  <tr>
    <td><%= index+1 %></td>
    <td><%= bar.name %></td>
    <td><%= bar.price %></td>
    <td><%= bar.address %></td>
    <td>
      <% if !bar.start_happy.nil? && !bar.end_happy.nil? && bar.start_happy != bar.end_happy %>
        <%= bar.start_happy.strftime("%R") %> - <%= bar.end_happy.strftime("%R") %>
      <% else %>
        no
      <% end %>
    </td>
    <td>
      <% if !bar.price_happy.nil? %>
        <%= bar.price_happy %>
      <% else %>
          no
      <% end %>
    </td>
    <td>
      <!--#{bar.created_at.strftime("Le %d/%m/%y à %R")}-->
      <%= "#{time_ago_in_words(bar.created_at)}" %>
    </td>
    <td>
      <%= link_to bar do %>
        <%= image_tag('icons/show.png')%>
      <% end %>
    </td>
    <td><%= link_to edit_bar_path(bar) do %>
      <%= image_tag('icons/edit.png')%>
      <% end %>
    </td>
    <td><%= link_to bar, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <%= image_tag('icons/delete.png')%>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

app/views/bars/new.html.erb
<div id="new-bar">
    <h2>Ajoutez un bar !</h2>
    <%= render 'form' %>
    <%= javascript_tag "autocompleteNew()" %>
</div>

app/views/bars/show.html.erb
<p id="notice"><%= notice %></p>


<div>
    <p>
      <b>Name:</b>
      <%= @bar.name %>
    </p>

    <p>
      <b>Price:</b>
      <%= @bar.price %>
    </p>

    <p>
      <b>Address:</b>
      <%= @bar.address %>
    </p>

      <h2>Comments</h2>
      <div id="comments">
        <%= render "comments/bar_comments" %>
      </div>

  <%= link_to 'Edit', edit_bar_path(@bar) %> |
    <%= link_to 'Back', bars_path %> -->
</div>