config/routes.rb
Payetapinte::Application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  resources :bars do
    resources :comments
  end

  resources :preview

  resources :page

  root :to => "welcome#index"

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @bars = Bar.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bars }
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper

  def transform_price(price, decimal)
    parts = price.to_s.split('.')

    if decimal
      if parts[1].to_i < 10
        newPrice = "#{parts[0]}<span>,#{parts[1]}0</span>".html_safe
      elsif parts[1].to_i > 10
        newPrice = "#{parts[0]}<span>,#{parts[1]}</span>".html_safe
      end
    else
      if parts[1].to_i == 0
        newPrice = "#{parts[0]}"
      elsif parts[1].to_i < 10
        newPrice = "#{parts[0]}<span>,#{parts[1]}0</span>".html_safe
      elsif parts[1].to_i > 10
        newPrice = "#{parts[0]}<span>,#{parts[1]}</span>".html_safe
      end
    end

    return newPrice
  end

  def dont_show_country(address)
    country = ", France"
    cp = /[0-9]{5}/
    return address.gsub(country, '').gsub(cp,'')
  end
end

app/views/welcome/index.html.erb
<p class="notice" style="display:none;"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div id="fb-root"></div>

<div id="header" class="noBounce">
  <%= image_tag "Logo.png" %>

  <div id="btn-opt">
    <%= image_tag "icons/loupe.png" %>
  </div>
  <div id="btn-menu">
    <%= image_tag "icons/menu-btn@2x.png", id:'menu-icon' %>
    <%= image_tag "icons/close-btn@2x.png", id:'close-icon', style:'display:none;'%>
  </div>
</div>
<div id="options">
  <div id="search">
    <input id="pac-input" class="controls" type="search" placeholder="Voir les bars à..." >
  </div>
</div>
<div id="menu">
  <ul>
    <li class="triangle"></li>
    <li>
      <div class="icon">
        <%= image_tag "icons/addbar@x2.png" %>
      </div>
      <%= link_to "Suggérer un bar", '#', id:'submission-btn' %>
    </li>

    <li class="fb-connect">
      <% if current_user %>
          <div class="icon">
            <%= image_tag current_user.image, class:'user-img' %>
          </div>
          <span class="user-name"><%= current_user.name %></span>
          <span class="signout"><%= link_to "Déconnexion", signout_path, id: "sign_out" %></span>
      <% else %>
          <div class="icon">
            <%= image_tag "icons/fb@2x.png" %>
          </div>
          <span class='signin'><%= link_to "Connectez-vous via Facebook", "/auth/facebook", id: "sign_in" %></span>
      <% end %>
    </li>
  </ul>
  <div id="user_nav">

  </div>
</div>

<div id="full-popin" style='display:none'>
   <!--call ajax here-->
</div>
  
<div id="map"></div>

<div id="bars">
  <div id="languette" class="noBounce"><%= image_tag "icons/languette.png" %></div>
  <div id="cache-container" class="noBounce">
    <div id="bars-container" class="noBounce"></div>
  </div>

  <div id="page-container">
    <div id="bar-page"></div>
  </div>
  <div id="nobar" style="display:none;">
    <div class="container">
      <p>Aucun Bar trouvé aux alentours ! </br> <span>Vous connaissez un bar dans le coin ? </br> <a id='open-submission' href="#">Soumettez le à Paye Ta Pinte!</a></span></p>
    </div>
  </div>
</div>

<!--<div id="fb"></div>-->